// -------------------------------------------------------------
// 
// File Name: F:\verilogTest\2nd\hdlsrc\NonCIC_Final\First_Block_H2_z_1.v
// Created: 2022-03-05 12:50:35
// 
// Generated by MATLAB 9.9 and HDL Coder 3.17
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: First_Block_H2_z_1
// Source Path: NonCIC_Final/Non-recursive CIC1/First Block H2(z)1
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module First_Block_H2_z_1
          (clk,
           enb_1_24_0,
           In1,
           Out1);


  input   clk;
  input   enb_1_24_0;
  input   signed [31:0] In1;  // sfix32_En28
  output  signed [48:0] Out1;  // sfix49_En45


  reg signed [31:0] Delay_out1;  // sfix32_En28
  wire signed [32:0] Add_add_cast;  // sfix33_En28
  wire signed [32:0] Add_add_cast_1;  // sfix33_En28
  wire signed [32:0] Add_out1;  // sfix33_En28
  wire signed [52:0] Gain_cast;  // sfix53_En47
  wire signed [51:0] Gain_cast_1;  // sfix52_En47
  wire signed [32:0] Gain_out1;  // sfix33_En29
  reg signed [32:0] Delay1_out1;  // sfix33_En29
  wire signed [33:0] Add1_add_cast;  // sfix34_En29
  wire signed [33:0] Add1_add_cast_1;  // sfix34_En29
  wire signed [33:0] Add1_out1;  // sfix34_En29
  wire signed [53:0] Gain1_cast;  // sfix54_En48
  wire signed [52:0] Gain1_cast_1;  // sfix53_En48
  wire signed [32:0] Gain1_out1;  // sfix33_En30
  reg signed [32:0] Delay2_out1;  // sfix33_En30
  wire signed [33:0] Add2_add_cast;  // sfix34_En30
  wire signed [33:0] Add2_add_cast_1;  // sfix34_En30
  wire signed [33:0] Add2_out1;  // sfix34_En30
  wire signed [53:0] Gain2_cast;  // sfix54_En49
  wire signed [52:0] Gain2_cast_1;  // sfix53_En49
  wire signed [34:0] Gain2_out1;  // sfix35_En31
  reg signed [34:0] Delay3_out1;  // sfix35_En31
  wire signed [35:0] Add3_add_cast;  // sfix36_En31
  wire signed [35:0] Add3_add_cast_1;  // sfix36_En31
  wire signed [35:0] Add3_add_temp;  // sfix36_En31
  wire signed [34:0] Add3_out1;  // sfix35_En31
  wire signed [54:0] Gain3_cast;  // sfix55_En50
  wire signed [53:0] Gain3_cast_1;  // sfix54_En50
  wire signed [35:0] Gain3_out1;  // sfix36_En32
  reg signed [35:0] Delay4_out1;  // sfix36_En32
  wire signed [36:0] Add4_add_cast;  // sfix37_En32
  wire signed [36:0] Add4_add_cast_1;  // sfix37_En32
  wire signed [36:0] Add4_add_temp;  // sfix37_En32
  wire signed [35:0] Add4_out1;  // sfix36_En32
  wire signed [55:0] Gain4_cast;  // sfix56_En51
  wire signed [54:0] Gain4_cast_1;  // sfix55_En51
  wire signed [36:0] Gain4_out1;  // sfix37_En33
  reg signed [36:0] Delay5_out1;  // sfix37_En33
  wire signed [37:0] Add5_add_cast;  // sfix38_En33
  wire signed [37:0] Add5_add_cast_1;  // sfix38_En33
  wire signed [37:0] Add5_add_temp;  // sfix38_En33
  wire signed [36:0] Add5_out1;  // sfix37_En33
  wire signed [56:0] Gain5_cast;  // sfix57_En52
  wire signed [55:0] Gain5_cast_1;  // sfix56_En52
  wire signed [38:0] Gain5_out1;  // sfix39_En34
  reg signed [38:0] Delay6_out1;  // sfix39_En34
  wire signed [37:0] Add6_add_cast;  // sfix38_En34
  wire signed [38:0] Add6_add_cast_1;  // sfix39_En34
  wire signed [37:0] Add6_add_cast_2;  // sfix38_En34
  wire signed [38:0] Add6_add_cast_3;  // sfix39_En34
  wire signed [38:0] Add6_add_temp;  // sfix39_En34
  wire signed [37:0] Add6_out1;  // sfix38_En34
  wire signed [57:0] Gain6_cast;  // sfix58_En53
  wire signed [56:0] Gain6_cast_1;  // sfix57_En53
  wire signed [38:0] Gain6_out1;  // sfix39_En35
  reg signed [38:0] Delay7_out1;  // sfix39_En35
  wire signed [39:0] Add7_add_cast;  // sfix40_En35
  wire signed [39:0] Add7_add_cast_1;  // sfix40_En35
  wire signed [39:0] Add7_add_temp;  // sfix40_En35
  wire signed [38:0] Add7_out1;  // sfix39_En35
  wire signed [58:0] Gain7_cast;  // sfix59_En54
  wire signed [57:0] Gain7_cast_1;  // sfix58_En54
  wire signed [39:0] Gain7_out1;  // sfix40_En36
  reg signed [39:0] Delay8_out1;  // sfix40_En36
  wire signed [40:0] Add8_add_cast;  // sfix41_En36
  wire signed [40:0] Add8_add_cast_1;  // sfix41_En36
  wire signed [40:0] Add8_add_temp;  // sfix41_En36
  wire signed [39:0] Add8_out1;  // sfix40_En36
  wire signed [59:0] Gain8_cast;  // sfix60_En55
  wire signed [58:0] Gain8_cast_1;  // sfix59_En55
  wire signed [40:0] Gain8_out1;  // sfix41_En37
  reg signed [40:0] Delay9_out1;  // sfix41_En37
  wire signed [41:0] Add9_add_cast;  // sfix42_En37
  wire signed [41:0] Add9_add_cast_1;  // sfix42_En37
  wire signed [41:0] Add9_add_temp;  // sfix42_En37
  wire signed [40:0] Add9_out1;  // sfix41_En37
  wire signed [60:0] Gain9_cast;  // sfix61_En56
  wire signed [59:0] Gain9_cast_1;  // sfix60_En56
  wire signed [41:0] Gain9_out1;  // sfix42_En38
  reg signed [41:0] Delay10_out1;  // sfix42_En38
  wire signed [42:0] Add10_add_cast;  // sfix43_En38
  wire signed [42:0] Add10_add_cast_1;  // sfix43_En38
  wire signed [42:0] Add10_add_temp;  // sfix43_En38
  wire signed [41:0] Add10_out1;  // sfix42_En38
  wire signed [61:0] Gain10_cast;  // sfix62_En57
  wire signed [60:0] Gain10_cast_1;  // sfix61_En57
  wire signed [42:0] Gain10_out1;  // sfix43_En39
  reg signed [42:0] Delay11_out1;  // sfix43_En39
  wire signed [43:0] Add11_add_cast;  // sfix44_En39
  wire signed [43:0] Add11_add_cast_1;  // sfix44_En39
  wire signed [43:0] Add11_add_temp;  // sfix44_En39
  wire signed [42:0] Add11_out1;  // sfix43_En39
  wire signed [62:0] Gain11_cast;  // sfix63_En58
  wire signed [61:0] Gain11_cast_1;  // sfix62_En58
  wire signed [43:0] Gain11_out1;  // sfix44_En40
  reg signed [43:0] Delay12_out1;  // sfix44_En40
  wire signed [44:0] Add12_add_cast;  // sfix45_En40
  wire signed [44:0] Add12_add_cast_1;  // sfix45_En40
  wire signed [44:0] Add12_add_temp;  // sfix45_En40
  wire signed [43:0] Add12_out1;  // sfix44_En40
  wire signed [63:0] Gain12_cast;  // sfix64_En59
  wire signed [62:0] Gain12_cast_1;  // sfix63_En59
  wire signed [44:0] Gain12_out1;  // sfix45_En41
  reg signed [44:0] Delay13_out1;  // sfix45_En41
  wire signed [45:0] Add13_add_cast;  // sfix46_En41
  wire signed [45:0] Add13_add_cast_1;  // sfix46_En41
  wire signed [45:0] Add13_add_temp;  // sfix46_En41
  wire signed [44:0] Add13_out1;  // sfix45_En41
  wire signed [64:0] Gain13_cast;  // sfix65_En60
  wire signed [63:0] Gain13_cast_1;  // sfix64_En60
  wire signed [45:0] Gain13_out1;  // sfix46_En42
  reg signed [45:0] Delay14_out1;  // sfix46_En42
  wire signed [46:0] Add14_add_cast;  // sfix47_En42
  wire signed [46:0] Add14_add_cast_1;  // sfix47_En42
  wire signed [46:0] Add14_add_temp;  // sfix47_En42
  wire signed [45:0] Add14_out1;  // sfix46_En42
  wire signed [65:0] Gain14_cast;  // sfix66_En61
  wire signed [64:0] Gain14_cast_1;  // sfix65_En61
  wire signed [46:0] Gain14_out1;  // sfix47_En43
  reg signed [46:0] Delay15_out1;  // sfix47_En43
  wire signed [47:0] Add15_add_cast;  // sfix48_En43
  wire signed [47:0] Add15_add_cast_1;  // sfix48_En43
  wire signed [47:0] Add15_add_temp;  // sfix48_En43
  wire signed [46:0] Add15_out1;  // sfix47_En43
  wire signed [66:0] Gain15_cast;  // sfix67_En62
  wire signed [65:0] Gain15_cast_1;  // sfix66_En62
  wire signed [47:0] Gain15_out1;  // sfix48_En44
  reg signed [47:0] Delay16_out1;  // sfix48_En44
  wire signed [48:0] Add16_add_cast;  // sfix49_En44
  wire signed [48:0] Add16_add_cast_1;  // sfix49_En44
  wire signed [48:0] Add16_add_temp;  // sfix49_En44
  wire signed [47:0] Add16_out1;  // sfix48_En44
  wire signed [67:0] Gain16_cast;  // sfix68_En63
  wire signed [66:0] Gain16_cast_1;  // sfix67_En63
  wire signed [48:0] Gain16_out1;  // sfix49_En45


  always @(posedge clk)
    begin : Delay_rsvd_process
      if (enb_1_24_0) begin
        Delay_out1 <= In1;
      end
    end



  assign Add_add_cast = {In1[31], In1};
  assign Add_add_cast_1 = {Delay_out1[31], Delay_out1};
  assign Add_out1 = Add_add_cast + Add_add_cast_1;



  assign Gain_cast = {{2{Add_out1[32]}}, {Add_out1, 18'b000000000000000000}};
  assign Gain_cast_1 = Gain_cast[51:0];
  assign Gain_out1 = (((Gain_cast_1[51] == 1'b0) && (Gain_cast_1[50] != 1'b0)) || ((Gain_cast_1[51] == 1'b0) 
    && (Gain_cast_1[50:18] == 33'sh0FFFFFFFF)) ? 33'sh0FFFFFFFF :
              ((Gain_cast_1[51] == 1'b1) && (Gain_cast_1[50] != 1'b1) ? 33'sh100000000 :
              Gain_cast_1[50:18] + $signed({1'b0, Gain_cast_1[17]})));



  always @(posedge clk)
    begin : Delay1_process
      if (enb_1_24_0) begin
        Delay1_out1 <= Gain_out1;
      end
    end



  assign Add1_add_cast = {Gain_out1[32], Gain_out1};
  assign Add1_add_cast_1 = {Delay1_out1[32], Delay1_out1};
  assign Add1_out1 = Add1_add_cast + Add1_add_cast_1;



  assign Gain1_cast = {{2{Add1_out1[33]}}, {Add1_out1, 18'b000000000000000000}};
  assign Gain1_cast_1 = Gain1_cast[52:0];
  assign Gain1_out1 = (((Gain1_cast_1[52] == 1'b0) && (Gain1_cast_1[51:50] != 2'b00)) || ((Gain1_cast_1[52] 
    == 1'b0) && (Gain1_cast_1[50:18] == 33'sh0FFFFFFFF)) ? 33'sh0FFFFFFFF :
              ((Gain1_cast_1[52] == 1'b1) && (Gain1_cast_1[51:50] != 2'b11) ? 33'sh100000000 :
              Gain1_cast_1[50:18] + $signed({1'b0, Gain1_cast_1[17]})));



  always @(posedge clk)
    begin : Delay2_process
      if (enb_1_24_0) begin
        Delay2_out1 <= Gain1_out1;
      end
    end



  assign Add2_add_cast = {Gain1_out1[32], Gain1_out1};
  assign Add2_add_cast_1 = {Delay2_out1[32], Delay2_out1};
  assign Add2_out1 = Add2_add_cast + Add2_add_cast_1;



  assign Gain2_cast = {{2{Add2_out1[33]}}, {Add2_out1, 18'b000000000000000000}};
  assign Gain2_cast_1 = Gain2_cast[52:0];
  assign Gain2_out1 = ((Gain2_cast_1[52] == 1'b0) && (Gain2_cast_1[51:18] == 34'h3FFFFFFFF) ? 35'sh3FFFFFFFF :
              Gain2_cast_1[52:18] + $signed({1'b0, Gain2_cast_1[17]}));



  always @(posedge clk)
    begin : Delay3_process
      if (enb_1_24_0) begin
        Delay3_out1 <= Gain2_out1;
      end
    end



  assign Add3_add_cast = {Gain2_out1[34], Gain2_out1};
  assign Add3_add_cast_1 = {Delay3_out1[34], Delay3_out1};
  assign Add3_add_temp = Add3_add_cast + Add3_add_cast_1;
  assign Add3_out1 = ((Add3_add_temp[35] == 1'b0) && (Add3_add_temp[34] != 1'b0) ? 35'sh3FFFFFFFF :
              ((Add3_add_temp[35] == 1'b1) && (Add3_add_temp[34] != 1'b1) ? 35'sh400000000 :
              $signed(Add3_add_temp[34:0])));



  assign Gain3_cast = {{2{Add3_out1[34]}}, {Add3_out1, 18'b000000000000000000}};
  assign Gain3_cast_1 = Gain3_cast[53:0];
  assign Gain3_out1 = ((Gain3_cast_1[53] == 1'b0) && (Gain3_cast_1[52:18] == 35'h7FFFFFFFF) ? 36'sh7FFFFFFFF :
              Gain3_cast_1[53:18] + $signed({1'b0, Gain3_cast_1[17]}));



  always @(posedge clk)
    begin : Delay4_process
      if (enb_1_24_0) begin
        Delay4_out1 <= Gain3_out1;
      end
    end



  assign Add4_add_cast = {Gain3_out1[35], Gain3_out1};
  assign Add4_add_cast_1 = {Delay4_out1[35], Delay4_out1};
  assign Add4_add_temp = Add4_add_cast + Add4_add_cast_1;
  assign Add4_out1 = ((Add4_add_temp[36] == 1'b0) && (Add4_add_temp[35] != 1'b0) ? 36'sh7FFFFFFFF :
              ((Add4_add_temp[36] == 1'b1) && (Add4_add_temp[35] != 1'b1) ? 36'sh800000000 :
              $signed(Add4_add_temp[35:0])));



  assign Gain4_cast = {{2{Add4_out1[35]}}, {Add4_out1, 18'b000000000000000000}};
  assign Gain4_cast_1 = Gain4_cast[54:0];
  assign Gain4_out1 = ((Gain4_cast_1[54] == 1'b0) && (Gain4_cast_1[53:18] == 36'hFFFFFFFFF) ? 37'sh0FFFFFFFFF 
    :
              Gain4_cast_1[54:18] + $signed({1'b0, Gain4_cast_1[17]}));



  always @(posedge clk)
    begin : Delay5_process
      if (enb_1_24_0) begin
        Delay5_out1 <= Gain4_out1;
      end
    end



  assign Add5_add_cast = {Gain4_out1[36], Gain4_out1};
  assign Add5_add_cast_1 = {Delay5_out1[36], Delay5_out1};
  assign Add5_add_temp = Add5_add_cast + Add5_add_cast_1;
  assign Add5_out1 = ((Add5_add_temp[37] == 1'b0) && (Add5_add_temp[36] != 1'b0) ? 37'sh0FFFFFFFFF :
              ((Add5_add_temp[37] == 1'b1) && (Add5_add_temp[36] != 1'b1) ? 37'sh1000000000 :
              $signed(Add5_add_temp[36:0])));



  assign Gain5_cast = {{2{Add5_out1[36]}}, {Add5_out1, 18'b000000000000000000}};
  assign Gain5_cast_1 = Gain5_cast[55:0];
  assign Gain5_out1 = ({Gain5_cast_1[55], Gain5_cast_1[55:18]}) + $signed({1'b0, Gain5_cast_1[17]});



  always @(posedge clk)
    begin : Delay6_process
      if (enb_1_24_0) begin
        Delay6_out1 <= Gain5_out1;
      end
    end



  assign Add6_add_cast = ((Gain5_out1[38] == 1'b0) && (Gain5_out1[37] != 1'b0) ? 38'sh1FFFFFFFFF :
              ((Gain5_out1[38] == 1'b1) && (Gain5_out1[37] != 1'b1) ? 38'sh2000000000 :
              $signed(Gain5_out1[37:0])));
  assign Add6_add_cast_1 = {Add6_add_cast[37], Add6_add_cast};
  assign Add6_add_cast_2 = ((Delay6_out1[38] == 1'b0) && (Delay6_out1[37] != 1'b0) ? 38'sh1FFFFFFFFF :
              ((Delay6_out1[38] == 1'b1) && (Delay6_out1[37] != 1'b1) ? 38'sh2000000000 :
              $signed(Delay6_out1[37:0])));
  assign Add6_add_cast_3 = {Add6_add_cast_2[37], Add6_add_cast_2};
  assign Add6_add_temp = Add6_add_cast_1 + Add6_add_cast_3;
  assign Add6_out1 = ((Add6_add_temp[38] == 1'b0) && (Add6_add_temp[37] != 1'b0) ? 38'sh1FFFFFFFFF :
              ((Add6_add_temp[38] == 1'b1) && (Add6_add_temp[37] != 1'b1) ? 38'sh2000000000 :
              $signed(Add6_add_temp[37:0])));



  assign Gain6_cast = {{2{Add6_out1[37]}}, {Add6_out1, 18'b000000000000000000}};
  assign Gain6_cast_1 = Gain6_cast[56:0];
  assign Gain6_out1 = ((Gain6_cast_1[56] == 1'b0) && (Gain6_cast_1[55:18] == 38'h3FFFFFFFFF) ? 
    39'sh3FFFFFFFFF :
              Gain6_cast_1[56:18] + $signed({1'b0, Gain6_cast_1[17]}));



  always @(posedge clk)
    begin : Delay7_process
      if (enb_1_24_0) begin
        Delay7_out1 <= Gain6_out1;
      end
    end



  assign Add7_add_cast = {Gain6_out1[38], Gain6_out1};
  assign Add7_add_cast_1 = {Delay7_out1[38], Delay7_out1};
  assign Add7_add_temp = Add7_add_cast + Add7_add_cast_1;
  assign Add7_out1 = ((Add7_add_temp[39] == 1'b0) && (Add7_add_temp[38] != 1'b0) ? 39'sh3FFFFFFFFF :
              ((Add7_add_temp[39] == 1'b1) && (Add7_add_temp[38] != 1'b1) ? 39'sh4000000000 :
              $signed(Add7_add_temp[38:0])));



  assign Gain7_cast = {{2{Add7_out1[38]}}, {Add7_out1, 18'b000000000000000000}};
  assign Gain7_cast_1 = Gain7_cast[57:0];
  assign Gain7_out1 = ((Gain7_cast_1[57] == 1'b0) && (Gain7_cast_1[56:18] == 39'h7FFFFFFFFF) ? 
    40'sh7FFFFFFFFF :
              Gain7_cast_1[57:18] + $signed({1'b0, Gain7_cast_1[17]}));



  always @(posedge clk)
    begin : Delay8_process
      if (enb_1_24_0) begin
        Delay8_out1 <= Gain7_out1;
      end
    end



  assign Add8_add_cast = {Gain7_out1[39], Gain7_out1};
  assign Add8_add_cast_1 = {Delay8_out1[39], Delay8_out1};
  assign Add8_add_temp = Add8_add_cast + Add8_add_cast_1;
  assign Add8_out1 = ((Add8_add_temp[40] == 1'b0) && (Add8_add_temp[39] != 1'b0) ? 40'sh7FFFFFFFFF :
              ((Add8_add_temp[40] == 1'b1) && (Add8_add_temp[39] != 1'b1) ? 40'sh8000000000 :
              $signed(Add8_add_temp[39:0])));



  assign Gain8_cast = {{2{Add8_out1[39]}}, {Add8_out1, 18'b000000000000000000}};
  assign Gain8_cast_1 = Gain8_cast[58:0];
  assign Gain8_out1 = ((Gain8_cast_1[58] == 1'b0) && (Gain8_cast_1[57:18] == 40'hFFFFFFFFFF) ? 
    41'sh0FFFFFFFFFF :
              Gain8_cast_1[58:18] + $signed({1'b0, Gain8_cast_1[17]}));



  always @(posedge clk)
    begin : Delay9_process
      if (enb_1_24_0) begin
        Delay9_out1 <= Gain8_out1;
      end
    end



  assign Add9_add_cast = {Gain8_out1[40], Gain8_out1};
  assign Add9_add_cast_1 = {Delay9_out1[40], Delay9_out1};
  assign Add9_add_temp = Add9_add_cast + Add9_add_cast_1;
  assign Add9_out1 = ((Add9_add_temp[41] == 1'b0) && (Add9_add_temp[40] != 1'b0) ? 41'sh0FFFFFFFFFF :
              ((Add9_add_temp[41] == 1'b1) && (Add9_add_temp[40] != 1'b1) ? 41'sh10000000000 :
              $signed(Add9_add_temp[40:0])));



  assign Gain9_cast = {{2{Add9_out1[40]}}, {Add9_out1, 18'b000000000000000000}};
  assign Gain9_cast_1 = Gain9_cast[59:0];
  assign Gain9_out1 = ((Gain9_cast_1[59] == 1'b0) && (Gain9_cast_1[58:18] == 41'h1FFFFFFFFFF) ? 
    42'sh1FFFFFFFFFF :
              Gain9_cast_1[59:18] + $signed({1'b0, Gain9_cast_1[17]}));



  always @(posedge clk)
    begin : Delay10_process
      if (enb_1_24_0) begin
        Delay10_out1 <= Gain9_out1;
      end
    end



  assign Add10_add_cast = {Gain9_out1[41], Gain9_out1};
  assign Add10_add_cast_1 = {Delay10_out1[41], Delay10_out1};
  assign Add10_add_temp = Add10_add_cast + Add10_add_cast_1;
  assign Add10_out1 = ((Add10_add_temp[42] == 1'b0) && (Add10_add_temp[41] != 1'b0) ? 42'sh1FFFFFFFFFF :
              ((Add10_add_temp[42] == 1'b1) && (Add10_add_temp[41] != 1'b1) ? 42'sh20000000000 :
              $signed(Add10_add_temp[41:0])));



  assign Gain10_cast = {{2{Add10_out1[41]}}, {Add10_out1, 18'b000000000000000000}};
  assign Gain10_cast_1 = Gain10_cast[60:0];
  assign Gain10_out1 = ((Gain10_cast_1[60] == 1'b0) && (Gain10_cast_1[59:18] == 42'h3FFFFFFFFFF) ? 
    43'sh3FFFFFFFFFF :
              Gain10_cast_1[60:18] + $signed({1'b0, Gain10_cast_1[17]}));



  always @(posedge clk)
    begin : Delay11_process
      if (enb_1_24_0) begin
        Delay11_out1 <= Gain10_out1;
      end
    end



  assign Add11_add_cast = {Gain10_out1[42], Gain10_out1};
  assign Add11_add_cast_1 = {Delay11_out1[42], Delay11_out1};
  assign Add11_add_temp = Add11_add_cast + Add11_add_cast_1;
  assign Add11_out1 = ((Add11_add_temp[43] == 1'b0) && (Add11_add_temp[42] != 1'b0) ? 43'sh3FFFFFFFFFF :
              ((Add11_add_temp[43] == 1'b1) && (Add11_add_temp[42] != 1'b1) ? 43'sh40000000000 :
              $signed(Add11_add_temp[42:0])));



  assign Gain11_cast = {{2{Add11_out1[42]}}, {Add11_out1, 18'b000000000000000000}};
  assign Gain11_cast_1 = Gain11_cast[61:0];
  assign Gain11_out1 = ((Gain11_cast_1[61] == 1'b0) && (Gain11_cast_1[60:18] == 43'h7FFFFFFFFFF) ? 
    44'sh7FFFFFFFFFF :
              Gain11_cast_1[61:18] + $signed({1'b0, Gain11_cast_1[17]}));



  always @(posedge clk)
    begin : Delay12_process
      if (enb_1_24_0) begin
        Delay12_out1 <= Gain11_out1;
      end
    end



  assign Add12_add_cast = {Gain11_out1[43], Gain11_out1};
  assign Add12_add_cast_1 = {Delay12_out1[43], Delay12_out1};
  assign Add12_add_temp = Add12_add_cast + Add12_add_cast_1;
  assign Add12_out1 = ((Add12_add_temp[44] == 1'b0) && (Add12_add_temp[43] != 1'b0) ? 44'sh7FFFFFFFFFF :
              ((Add12_add_temp[44] == 1'b1) && (Add12_add_temp[43] != 1'b1) ? 44'sh80000000000 :
              $signed(Add12_add_temp[43:0])));



  assign Gain12_cast = {{2{Add12_out1[43]}}, {Add12_out1, 18'b000000000000000000}};
  assign Gain12_cast_1 = Gain12_cast[62:0];
  assign Gain12_out1 = ((Gain12_cast_1[62] == 1'b0) && (Gain12_cast_1[61:18] == 44'hFFFFFFFFFFF) ? 
    45'sh0FFFFFFFFFFF :
              Gain12_cast_1[62:18] + $signed({1'b0, Gain12_cast_1[17]}));



  always @(posedge clk)
    begin : Delay13_process
      if (enb_1_24_0) begin
        Delay13_out1 <= Gain12_out1;
      end
    end



  assign Add13_add_cast = {Gain12_out1[44], Gain12_out1};
  assign Add13_add_cast_1 = {Delay13_out1[44], Delay13_out1};
  assign Add13_add_temp = Add13_add_cast + Add13_add_cast_1;
  assign Add13_out1 = ((Add13_add_temp[45] == 1'b0) && (Add13_add_temp[44] != 1'b0) ? 45'sh0FFFFFFFFFFF :
              ((Add13_add_temp[45] == 1'b1) && (Add13_add_temp[44] != 1'b1) ? 45'sh100000000000 :
              $signed(Add13_add_temp[44:0])));



  assign Gain13_cast = {{2{Add13_out1[44]}}, {Add13_out1, 18'b000000000000000000}};
  assign Gain13_cast_1 = Gain13_cast[63:0];
  assign Gain13_out1 = ((Gain13_cast_1[63] == 1'b0) && (Gain13_cast_1[62:18] == 45'h1FFFFFFFFFFF) ? 
    46'sh1FFFFFFFFFFF :
              Gain13_cast_1[63:18] + $signed({1'b0, Gain13_cast_1[17]}));



  always @(posedge clk)
    begin : Delay14_process
      if (enb_1_24_0) begin
        Delay14_out1 <= Gain13_out1;
      end
    end



  assign Add14_add_cast = {Gain13_out1[45], Gain13_out1};
  assign Add14_add_cast_1 = {Delay14_out1[45], Delay14_out1};
  assign Add14_add_temp = Add14_add_cast + Add14_add_cast_1;
  assign Add14_out1 = ((Add14_add_temp[46] == 1'b0) && (Add14_add_temp[45] != 1'b0) ? 46'sh1FFFFFFFFFFF :
              ((Add14_add_temp[46] == 1'b1) && (Add14_add_temp[45] != 1'b1) ? 46'sh200000000000 :
              $signed(Add14_add_temp[45:0])));



  assign Gain14_cast = {{2{Add14_out1[45]}}, {Add14_out1, 18'b000000000000000000}};
  assign Gain14_cast_1 = Gain14_cast[64:0];
  assign Gain14_out1 = ((Gain14_cast_1[64] == 1'b0) && (Gain14_cast_1[63:18] == 46'h3FFFFFFFFFFF) ? 
    47'sh3FFFFFFFFFFF :
              Gain14_cast_1[64:18] + $signed({1'b0, Gain14_cast_1[17]}));



  always @(posedge clk)
    begin : Delay15_process
      if (enb_1_24_0) begin
        Delay15_out1 <= Gain14_out1;
      end
    end



  assign Add15_add_cast = {Gain14_out1[46], Gain14_out1};
  assign Add15_add_cast_1 = {Delay15_out1[46], Delay15_out1};
  assign Add15_add_temp = Add15_add_cast + Add15_add_cast_1;
  assign Add15_out1 = ((Add15_add_temp[47] == 1'b0) && (Add15_add_temp[46] != 1'b0) ? 47'sh3FFFFFFFFFFF :
              ((Add15_add_temp[47] == 1'b1) && (Add15_add_temp[46] != 1'b1) ? 47'sh400000000000 :
              $signed(Add15_add_temp[46:0])));



  assign Gain15_cast = {{2{Add15_out1[46]}}, {Add15_out1, 18'b000000000000000000}};
  assign Gain15_cast_1 = Gain15_cast[65:0];
  assign Gain15_out1 = ((Gain15_cast_1[65] == 1'b0) && (Gain15_cast_1[64:18] == 47'h7FFFFFFFFFFF) ? 
    48'sh7FFFFFFFFFFF :
              Gain15_cast_1[65:18] + $signed({1'b0, Gain15_cast_1[17]}));



  always @(posedge clk)
    begin : Delay16_process
      if (enb_1_24_0) begin
        Delay16_out1 <= Gain15_out1;
      end
    end



  assign Add16_add_cast = {Gain15_out1[47], Gain15_out1};
  assign Add16_add_cast_1 = {Delay16_out1[47], Delay16_out1};
  assign Add16_add_temp = Add16_add_cast + Add16_add_cast_1;
  assign Add16_out1 = ((Add16_add_temp[48] == 1'b0) && (Add16_add_temp[47] != 1'b0) ? 48'sh7FFFFFFFFFFF :
              ((Add16_add_temp[48] == 1'b1) && (Add16_add_temp[47] != 1'b1) ? 48'sh800000000000 :
              $signed(Add16_add_temp[47:0])));



  assign Gain16_cast = {{2{Add16_out1[47]}}, {Add16_out1, 18'b000000000000000000}};
  assign Gain16_cast_1 = Gain16_cast[66:0];
  assign Gain16_out1 = ((Gain16_cast_1[66] == 1'b0) && (Gain16_cast_1[65:18] == 48'hFFFFFFFFFFFF) ? 
    49'sh0FFFFFFFFFFFF :
              Gain16_cast_1[66:18] + $signed({1'b0, Gain16_cast_1[17]}));



  assign Out1 = Gain16_out1;

endmodule  // First_Block_H2_z_1

